/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.26.4-gb56144f (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.26.4-gb56144f"
#endif
#define SDL_REVISION_NUMBER 0
